<?php

/**
 * PluginmdConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginmdConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginmdConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginmdConfig');
    }
}