generator:
  class: sfDoctrineGenerator
  param:
    model_class:           mdConfig
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          md_config
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
      fields:  ~
      list:    
        title:  Configuración
#        actions: []
        batch_actions: {}
        object_actions: { _edit: ~ }
        max_per_page: 50
      filter:  ~
      form: 
        actions: []
      edit:
        title: Editar
        actions: { _save: ~ , _list: ~ }
      new:
        actions: { _save: ~ }
